### ISSUE TITLE
MAc Client?

### ISSUE THREAD

**Issue by BaddMann** [Graylog2/collector-sidecar#118]
### Problem description
Want to log Windows, Linux and Windows servers and Clients.
Windows and Linux are working, Mac....

### Steps to reproduce the problem

1. Find mac install or build from source?

### Environment

* Sidecar Version: Latest
* Graylog Version: Latest Docker Version
* Operating System: MAcintosh 10.11.X
* Elasticsearch Version:Latest Docker Version
* MongoDB Version:Latest Docker Version

**Comment by mariussturm** [comment]
Hi,
macOS is not supported by the Sidecar. Since the Sidecar is only writing configuration files and then starts Nxlog or Filebeat, you are of cause free to to use one of those directly on macOS. The typical use case is more about managing a remote server fleet in an easy way, not so much about desktop devices.

**Comment by mariussturm** [comment]
Having said that, we will evaluate if it could make sense to deploy to desktop machines including macOS over here: https://github.com/Graylog2/collector-sidecar/issues/119

**Comment by BaddMann** [comment]
Thank you for the consideration

**Comment by joschi** [comment]
@scottcc Since Go does indeed support creating binaries for macOS, you can probably compile a version for Darwin (see https://github.com/golang/go/wiki/Darwin) and use Filebeat as log shipper.

This being said, we don't support officially macOS/Darwin and subsequently don't test releases on macOS/Darwin.

**Comment by jabenninghoff** [comment]
Hi @scottcc thanks! I got as far as building the formula but still haven't got it into production for my setup. Let me know if there are issues...

**Comment by scottcc** [comment]
Happy to say this has been in production now for over a month - no issues whatsoever. Very nice work.
