### ISSUE TITLE
Docker deployment of the collector?

### ISSUE THREAD

**Issue by eric-tucker** [Graylog2/collector-sidecar#131]
We use Docker for everything, so the idea of installing packages directly on the system isn't the most ideal for us.

I attempted to make my own Dockerfile that sets up the collector, but I don't see how to simply run the collector in non-daemon mode.  Is there an executable I can run in the foreground?

**Comment by mariussturm** [comment]
Yes, you can download the tar-ball and execute the binary for your system in foreground. That should work fine in a container. However, I am not sure if the Sidecar is the right solution then. It's more a remote configuration tool rather than a collector. So you could also start nxlog or filebeat directly in the container.

**Comment by eric-tucker** [comment]
I must be reading the docs wrong then. I thought the collector plus beats runs on the server where logs are in order to forward to the graylog server.

**Comment by mariussturm** [comment]
The sidecar is basically a solution to configure nxlog/filebeat from the Graylog web interface. If that makes sense in your environment go for it. But you can also run nxlog/filebeat without it and write your own configuration file by hand. As I said it highly depends on your use case, just try it and see if it's the right solution for a containerized environment.
