### ISSUE TITLE
Sidecar Installation (Update) (Windows) overwrites the config file

### ISSUE THREAD

**Issue by planki** [Graylog2/collector-sidecar#140]
### Problem description

Collector Install (Update) within Windows overwrites the collector_sidecar.yml if present.
It shouldn't overwrite this during an update.

### Steps to reproduce the problem

1. Update (Install) Sidecar on Windows

### Environment

* Sidecar Version: 0.1.0-rc1
* Graylog Version:  2.1.2
* Operating System: Windows Server 2012 R2
* Elasticsearch Version: xxx
* MongoDB Version: xxx

**Comment by mariussturm** [comment]
Will be fixed in the next release: https://github.com/Graylog2/collector-sidecar/commit/8f9ec58538d93c5d7018c88b2500083c03326cce
Please notice that the configuration file distributed by the package is still copied to collector_sidecar.yml.dist. In that way you can check for new configuration parameters after the update.
