### ISSUE TITLE
Do you guys know the sidecar compatible with win server 2000 ?

### ISSUE THREAD

**Issue by lukaforever85** [Graylog2/collector-sidecar#186]
### Problem description
 side car download compatible with windows 2000

### Steps to reproduce the problem

1. ... install win 2000

it does not run the service every download i tried! please i need help at this .

### Environment

* Sidecar Version:?
* Graylog Version:2
* Operating System: win server 2000
* Elasticsearch Version: last
* MongoDB Version: last

whit all others microsoft products its is a great tool to report.

**Comment by joschi** [comment]
@lukaforever85 I haven't tested it, but my guess is no simply because Go 1.3 removed support for Windows 2000: https://golang.org/doc/go1.3#win2000

For what it's worth, using nxlog directly on Windows 2000 (without the Graylog Collector Sidecar) should work: https://nxlog.co/documentation/nxlog-community-edition-reference-manual-v20928#im_mseventlog
