### ISSUE TITLE
Newline is broken on Windows when using Beats snippets

### ISSUE THREAD

**Issue by shodanshok** [Graylog2/collector-sidecar#232]
### Problem description

Creating a Beats snippet which extends on multiple lines does not work on Windows.
For example, the following snippets:
```
winlogbeat:
  event_logs:
  - name: Application
    ignoreolder: 168h
  - name: System
  - name: Security
```

produces (on Windows) the following one-liner:

`winlogbeat:  event_logs:   - name: Application     ignoreolder: 168h   - name: System   - name: Security`

which clearly breaks the Windows client.

Checking the source code, I think the problematic entry is [here:](https://github.com/Graylog2/collector-sidecar/blob/master/backends/beats/winlogbeat/render.go#L43) it should use the platform-specific newline escape rather than hardcoding `\n`

### Steps to reproduce the problem

1. install collector-sidecar on a Windows machine;
2. create a multi-line Beats configuration snippet;
3. use notepad to check for the generated configuration on the Windows machine: the multi-line snipped will be "flattened" on a single line (it opens correctly with Wordpad, which understand Unix line termination);
4. the collector-sidecar instance will be marked as "failed" on graylog server.

### Environment

* Sidecar Version: 0.1.5, [this file](https://github.com/Graylog2/collector-sidecar/releases/download/0.1.5/collector_sidecar_installer_0.1.5-1.exe)
* Graylog Version: 2.4.3-1
* Operating System: CentOS 7 (server) and Windows 2008R2 (client)
* Elasticsearch Version: 5.6.9-1
* MongoDB Version: 3.6.4-1

**Comment by manicholls** [comment]
I can confirm I'm seeing the same issue.  I'm unable to add any snippets at this time and haven't found a work around.

**Comment by shodanshok** [comment]
@mdobson90 I worked around the problem by using nxlog, buy using winlogbeat would be easier (as it is already distributed with the sidecar package).

**Comment by mdobson90** [comment]
Thanks, I agree NXLog probably works and I'd thought about using it, but I've got so far with winlogbeat and everything works as we need them, bar the snippets. 
GL2 is obviously fantastic for free - cannot fault it, but things that are packaged should work - if we were paying for the service I'd be a lot more hacked off that features dont work.
Hopefully it will be rectified in the next release of collector-sidecar.

As an aside, you can filter event ID's (include= "xxxx" or remove= "-XXXX") by using snippet on one line of: 
"    event_id: 4624, 4625, 4648, 4748, 4720, 4722, 4723, 4724, 4725, 4726, 4728, 4732, 4756, 4735, 4740, 4767, 4777, 4782, 4781"
(The initial spacing is important due to the yaml).
This works, but has a limit of 22 event ID's before it breaks.

**Comment by mariussturm** [comment]
There will be a new user interface in Graylog 3.0 for the Sidecar. The issue should be obsolete with that.

**Comment by shodanshok** [comment]
@mariussturm As the fix should be very easy to implement, it seems wrong to wait for Graylog version 3.0. A minor 2.4.x point release should be adequate.

**Comment by mariussturm** [comment]
Please test the 0.1.6 release with Graylog 2.4.x https://github.com/Graylog2/collector-sidecar/releases/tag/0.1.6

**Comment by mdobson90** [comment]
Can confirm this works perfectly in the 0.1.6 release - Many thanks to all involved, this was truly my only (un-workaround-able) issue with Graylog / Collector Sidecar.

All of the kudos.
