### ISSUE TITLE
Exec option for inputs/outputs?

### ISSUE THREAD

**Issue by jwoodard80** [Graylog2/collector-sidecar#26]
Would it be possible to rework the inputs / outputs interface for just a generalized "options" text area? My use case is below. I realize I could do this with a query statement but NXLog's own functions make this easier and having an options area I could really do either/or since it would just place my text at this location. I could also see writing more advanced things here without having to resort to using a snippet for a full configuration. I hope I have explained this properly... Thoughts?
```
<Input WindowsEventLog>
	Module im_msvistalog
	PollInterval 1
	SavePos	True
	ReadFromLast True
       Exec if ($Channel == "Security") drop();     <--	An options textarea that would place options here
</Input>
```
![image](https://cloud.githubusercontent.com/assets/10240627/16021867/8cff42c0-317a-11e6-9885-c1c150f82a26.png)

**Comment by mariussturm** [comment]
Hi,
thanks for the feedback! So the idea was to extend the Snippet section in a way that users can append them not only to the end of the configuration file but also to an Input or Output section.
So that you can define e snippet e.g. `Drop-Security`:
```
Exec if ($Channel == "Security") drop();
```
And that snippet can be associated with the  `WindowsEventLog`-Input and appended to that block.
Would that fix your issue?

**Comment by jwoodard80** [comment]
Hmm, trying to think through that.... I think that would work. 

Well, let me ask for clarification... I believe you are saying, I would be adding snippets to inputs/outputs correct? That sounds really good as I could have a snippet "repo" of things and add them as needed. However, the reverse (adding inputs to snippets) sounds like it would work but not as well.

Also, if the first is true, it would be nice to "stack" multiple snippets as well. As an example, I could create a snippet to filter security and another to filter Event ID 400 and 403. Both I could then apply to an input to combine them.  

But yes, I think this would work.... Is there an idea of a reasonable ETA on this?

**Comment by mariussturm** [comment]
Unfortunately it was a little hard from an UI perspective to extend the Snippets in the mentioned way so I went with a text area as your wrote in your description. It's collapsed by default because users can easily break the nxlog configuration with it but you can now add arbitrary strings to every nxlog in-/output. 948c5c490360024a7784422c70816e1c3372f151

**Comment by jwoodard80** [comment]
Thank you for doing this!

**Comment by hessmatt** [comment]
thank you, will this be in v2.0.4?

**Comment by mariussturm** [comment]
Yes, this is included in the next release.

**Comment by Linwood-F** [comment]
Should this be in 2.1.0-beta.1?

I was anxious to try it and (think) I installed it.  And in the log it says: 

[ServerBootstrap] Graylog server 2.1.0-beta.1+1b940e4 starting up

Under the collector page it shows "1.1.0-beta.1" and shows: 
1804898 Jul 25 12:20 graylog-plugin-collector-1.1.0-beta.1.jar 

Under the input of the collector I still see channel and query, but nowhere for arbitrary text, nor in the output section.
