### ISSUE TITLE
Release binaries for Linux/ARM (Raspberry Pi)

### ISSUE THREAD

**Issue by allangood** [Graylog2/collector-sidecar#271]
#### No binary released for Linux/ARM architecture (Raspberry Pi)
With the great popularity of Raspberry Pi, build binaries for this architecture will make this great tool even more popular and helps many non developers or beginners users to install and integrate embedded projects (like Weather Stations and others) with Graylog.

### Steps to reproduce the problem

No files released

### Environment

All

**Comment by mariussturm** [comment]
Hi,
we have made the decision that we don't provide official ARM binaries not long ago. There is a build target for it in the Makefile so you can compile it yourself relatively easy. The reason is that the support for more platforms need more resources that we don't have at the moment. This can change at any time in the future.

**Comment by awlx** [comment]
I made an automated build for armhf for FreifunkMUC maybe it helps others it can be found here:
http://apt.ffmuc.net/
