### ISSUE TITLE
Filebeat taking two much memory

### ISSUE THREAD

**Issue by kamal-bhatt** [Graylog2/collector-sidecar#275]
### Problem description
have configure the collector sidecar with filebeat output.after installing it is working fine.But my filebeat process taking more than 60% of the memory of my linux system
### Environment

* Sidecar Version:
* Graylog Version:
* Operating System:
ubuntu 16
* Elasticsearch Version:
* MongoDB Version:

**Comment by mariussturm** [comment]
Hi,
could you please post the complete filebeat configuration here?

**Comment by kamal-bhatt** [comment]
![image](https://user-images.githubusercontent.com/22490116/44334719-fd322280-a48f-11e8-9455-70fffc05e8ce.png)
![image](https://user-images.githubusercontent.com/22490116/44334752-0ae7a800-a490-11e8-9bca-d32a4f23c451.png)

**Comment by mariussturm** [comment]
If you use wildcard matches like `.../logs/*` Filebeat can generate some load on the host since it needs to go through all files in that directory and ingest them or at least figure out which one is actively written to. Did you try to disable one directory after the other to see which one is actually generating  the load?

However the Sidecar part looks correct from my point of view. Maybe you can ask the Elastic guys if they know of a situation where Filebeat is consuming too much memory?

**Comment by kamal-bhatt** [comment]
How can i set harvester limit setting into filebeat there is no option
