### ISSUE TITLE
Add additional informations to the sidecar that are transfered back to Graylog

### ISSUE THREAD

**Issue by jalogisch** [Graylog2/collector-sidecar#280]
### Problem description

When you have large fleet of sidecars it would be helpful when you can add additional information to the configuration that are transfered to Graylog and are then available. 
Like you can have `tags` that are attached to the sidecar to have decisions ( automated?) based on this tags.

**Comment by bitfactory-henno-schooljan** [comment]
Would it be possible to do this by setting additional Runtime variables in a sidecar.yml configuration, so that it is available through something like a `${sidecar.myOwnVariable}` in a configuration? This will allow for using the same configuration for all sidecars in the scenario where there are only small differences on servers, for instance when logs are located in different locations, but otherwise the same. That can prevent a lot of duplication.

**Comment by on3iropolos** [comment]
In my use case, we have multiple environments all pushing logs to the same graylog cluster. It would be helpful to create a custom variable like "datacenter_environment: PROD" in the sidecar.yml file, and use this variable on the collector which is otherwise identical per environment - ultimately resulting in a message field indicating the datacenter the log came from.

Currently I am relying on the full DNS name being accurate.

**Comment by boosty** [comment]
Hi everyone,

with Graylog 5.0 we released the possibility to automatically assign Sidecar configurations, based on tags.

A list of tags can be assigned in a Sidecar's YAML configuration. Collector configuration matching any of these tags will then automatically be applied to the Sidecar.

Details:
- https://github.com/Graylog2/graylog2-server/pull/13433
- https://go2docs.graylog.org/5-0/getting_in_log_data/graylog_sidecar.html?Highlight=sidecar#AssigningTags

Recently a related change was added to the Sidecar installer on Windows to accept tags at installation time, for convenience:
- https://github.com/Graylog2/collector-sidecar/pull/464
