### ISSUE TITLE
Fall back to Host name for Node_ID not working

### ISSUE THREAD

**Issue by jcspino** [Graylog2/collector-sidecar#35]
### Problem description
When I attempt to setup my collector_sidecar.yml file without a node_id entered graylog collector fails to start. I am given this error message when running the collector in debug mode, "Please provide a vaild node-id." I am also curious if there is something I do not understand about GitHub commits. I am using the installation for 0.0.8 downloaded from this link, https://github.com/Graylog2/collector-sidecar/releases, but it looks like that was released before the commit.  

### Steps to reproduce the problem

1. Install collector-sidecar on windows. 
2. remove the node id from the collector-sidecar.yml file
3. attempt to start graylog collector

### Environment

* Sidecar Version: 0.0.8
* Graylog Version: 2.0.2
* Operating System: windows 2003/2008/2012
* Elasticsearch Version:
* MongoDB Version:

This is the yml file I am using. I have also tried with the node id line removed completely. 

################## collector_sidecar.yml#####################
server_url: http://192.168.9.25:12900
collector_id: file:C:\Program Files\graylog\collector-sidecar\collector-id
node_id: 
tags:
    - IIS2003
log_path: C:\Program Files\graylog\collector-sidecar
update_interval: 10
backends:
    - name: nxlog
      enabled: true
      binary_path: C:\Program Files\nxlog\nxlog.exe
      configuration_path: C:\Program Files\nxlog\conf\nxlog.conf
################END####################

**Comment by jcspino** [comment]
sorry, the issue accidentally got submitted before I had filled out the form

**Comment by mariussturm** [comment]
Ok, for version 0.0.8 this bahavior is correct. We changed it after the release because some people were asking for an automatic fallback. But currently it's just in the code but not in a published release.
The general process goes like this: We develope new features and fix old bugs for some time, when the software is in a good state we compile and publish a new release. So even though this problem is fixed in the code you have to wait a little till 0.0.9 is available. Alternatively you can fetch the sources and compile the current development state yourself.
