### ISSUE TITLE
Match collectors binary whitelist case insensitive on Windows

### ISSUE THREAD

**Issue by mpfz0r** [Graylog2/collector-sidecar#364]
### Problem description

Windows filesystems are case insensitive.
We should make the `collectors_binary_whitelist` matching ignore case.

refs #363

**Comment by coffee-squirrel** [comment]
We got bit by this when installing the Sidecar on a shared system that was still running the Collector Sidecar.  The latter was installed to `C:\Program Files\graylog\collector-sidecar`, while the newer Sidecar would have installed to `C:\Program Files\Graylog\sidecar`.  Since the `graylog` directory already existed it was reused when the Sidecar got installed.

The Sidecar collector definitions reference `C:\Program Files\Graylog\sidecar\whatever.exe`, so we were getting [a `collectors_binary_whitelist` error](https://github.com/Graylog2/collector-sidecar/blob/1.0.2/backends/backend.go#L111).

We ended up just stopping the Windows services and renaming the directory from `graylog` to `Graylog`.
