### ISSUE TITLE
Filebeat - multiple outputs

### ISSUE THREAD

**Issue by pray4mojo** [Graylog2/collector-sidecar#57]
On boxes that send to one filebeat output the collector-sidecar is working great for me, but I'm still stuck on servers that have to send to multiple graylog inputs.  I know filebeat itself doesn't support multiple outputs for a single instance of filebeat.  I currently get around this with an ansible project that spins up multiple instances of filebeat, one for each output I need on a server.  Have you considered adding any such functionality to the collector-sidecar?

**Comment by mariussturm** [comment]
That can be pretty tricky, so it's not on the roadmap currently. What's the use case for this? Can't you just add a static field to an input on use that for seperation on the server?

**Comment by pray4mojo** [comment]
I've got web servers that i'm collecting apache and coldfusion logs from as well as Oracle applications servers running multiple app tiers (weblogic, Business intelligence, service bus, etc).  Things with wildly different log formats that I don't want to send through the same extractors.

**Comment by coffee-squirrel** [comment]
Ugh, I didn't realize Filebeat had that limitation.  I really wanted to get us off of nxlog, too.  We use several inputs to separate teams, environments, etc., assign unique static fields, and provide isolation for extractors.

If nothing else, it'd be good for the Web UI to indicate only one Beats output is possible (perhaps enforcing that to prevent confusion).

**Comment by mariussturm** [comment]
@coffee-squirrel yes, we could highlight this in the web UI.

**Comment by mariussturm** [comment]
We will gray out the output options once there is already a Filebeat or Winlogbeat output. In that way the user can't create a second one: https://github.com/Graylog2/graylog-plugin-collector/commit/0f183bc9e95ccbf872f8ca8f9adc2f2efcab374b

**Comment by dPanta** [comment]
Ideal solution would be if sidecar could theoretically launch multiple instances of filebeat honestly. Adding fields to messages per logtype for example is useless since I cannot use this for extractor management (ie. launch this extractor only for messages where field=value). Plus separation of configuration would be quite welcome as well. Having 50 separate applications on one server leads to having a collector configuration that has hundreds of file inputs and not having the ability to separate those via ports and configurations would be ideal.
