### ISSUE TITLE
Issues installing on 32-bit Windows servers

### ISSUE THREAD

**Issue by Wernervdmerwe** [Graylog2/collector-sidecar#66]
### Problem description
Attempting to install on Win2k3 32-bit server. Install works fine, but installing the service fails:
`C:\Program Files\graylog\collector-sidecar>graylog-collector-sidecar.exe -service install
panic: Failed to find GetTickCount64 procedure in kernel32: The specified procedure could not be found.

goroutine 1 [running]:
panic(0x7a8e20, 0x10eb1640)
        /opt/go/src/runtime/panic.go:481 +0x326
syscall.(*DLL).MustFindProc(0x10e68540, 0x831430, 0xe, 0x10e68570)
        /opt/go/src/syscall/dll_windows.go:110 +0x6c
github.com/Graylog2/collector-sidecar/vendor/github.com/cloudfoundry/gosigar.init()
        /go/src/github.com/Graylog2/collector-sidecar/vendor/github.com/cloudfoundry/gosigar/sigar_windows.go:21 +0x153
github.com/Graylog2/collector-sidecar/common.init()
        /go/src/github.com/Graylog2/collector-sidecar/common/sigar.go:162 +0x93
github.com/Graylog2/collector-sidecar/api/graylog.init()
        /go/src/github.com/Graylog2/collector-sidecar/api/graylog/responses.go:54 +0x3e
github.com/Graylog2/collector-sidecar/backends.init()
        /go/src/github.com/Graylog2/collector-sidecar/backends/registry.go:92 +0x48
main.init()
        /go/src/github.com/Graylog2/collector-sidecar/main.go:146 +0x66`

### Steps to reproduce the problem

1. Install on Win2k3 i386 server and run graylog-collector-sidecar.exe -service install

### Environment
* Sidecar Version: 0.0.9

**Comment by mariussturm** [comment]
Hi Werner,
we make use of gosigar in the sidecar. That library is not compatible with your windows version. Because of some other problems we just replaced that library with a better maintained fork. This could potentially fix your problem. But I was not able to find a virtual machine image or a vagrant box to validate this.
Please understand that we cant invest much time in an issue that only happens on an operating system that is 10+ years old.
You can test the latest changes in 0.1.0-alpha.1 https://github.com/Graylog2/collector-sidecar/releases/tag/0.1.0-alpha.1
