### ISSUE TITLE
Nxlog buffer and collector side car

### ISSUE THREAD

**Issue by ELmane** [Graylog2/collector-sidecar#72]
### Problem description

 Right now we are able to use 16Mb buffer. However it will be more practical if we can use messages bufferind and prioritizing in nxlog along with side car collector :

" Log messages can be buffered in memory or on disk in order to avoid loosing messages. Together with the nxlog language it is also possible to do conditional buffering based on different parameters (time or system load for example). Not all log sources are always equally important. Some systems send critical logs which should be processed at a higher priority than others. nxlog supports assigning priorities to log routes, this ensures that higher priority log messages are dealt with (read, processed and written/sent out) first, only then are the messages with lower priorities handled."
http://nxlog.co/products/nxlog-community-edition/features

### Environment

* Sidecar Version: 0.1.0-alpha.1
* Graylog Version: 2.0
* Operating System: centos

**Comment by mariussturm** [comment]
Sorry, what do you mean exactly? Maybe you can add a configuration example?

**Comment by mariussturm** [comment]
Currently I want to keep the buffer option as it is. I picked in-memory buffer intentionally to avoid problems like file write permissions or full disk situations. The buffer is unconditional because this would overload the web interface. In the end this is a compromise between usability and handling of edge cases. However if you really need sophisticated buffering this should be doable with custome snippet configurations.
